---
name: "AI Detectors"
version: "1.0.6"
slug: "ai_detectors"
description: "AI Detectors for snoring and sleeping pose"
startup: "application"
boot: "auto"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  SECRET_KEY: required
schema:
  SECRET_KEY: str
network:
  8001/tcp: 8001

host_network: true
privileged: 
  - SYS_ADMIN
  - SYS_RAWIO
  - DAC_READ_SEARCH
devices:
  - "/dev/snd:/dev/snd:rwm"  # Grant access to ALSA audio devices
audio: true  # Enable audio support