name: long_lived_token_sensor
version: dev 1.1.1
slug: long_lived_token_sensor
description: "this add on using long lived token for authentication"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - bmp180
  - bmp280
  - sht31
  - sht45
  - oxygen
options:
  addr-bmp: none
  addr-sht: none
  addr-oxy: none
  base_url: http://192.168.31.18:8123/api/states
    required: true
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkNGU2NDc0ZWM2ODU0OThlYmE1ZTIzYTMxOWUzMDY2MCIsImlhdCI6MTczNjMwNjI4MSwiZXhwIjoyMDUxNjY2MjgxfQ.BjyBI6G40FnMKlOMPIVN10rRnt4B3lseJj6-BDOCYOA
    required: true
  ssl: false
  bmp180: false
  bmp280: false
  sht31: false
  sht45: false
  oxygen: false
schema:
  base_url: str?
  token: str?
  bmp180: bool
  bmp280: bool
  sht31: bool
  sht45: bool
  oxygen: bool
  addr-bmp: list(0x76|0x77)
  addr-sht: list(0x44|0x45)
  addr-oxy: list(0x70|0x71|0x72|0x73)
devices:
  - "/dev/i2c-5:rwm"
