name: "Sleep Pad Monitor"
version: "1.0.0"
slug: "sleep_pad_monitor"
description: "A Home Assistant addon to read data from a Sleep Pad"
arch:
  - amd64
  - armv7
  - arm64
  - i386
startup: "application"
boot: "auto"
ports: {}
homeassistant: true
host_network: true
environment: []

image: "ghcr.io/home-assistant/amd64-base-python:3.9"
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.9"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.9"
  arm64: "ghcr.io/home-assistant/arm64-base-python:3.9"
