image: "ghcr.io/home-assistant/amd64-base-python:3.9"
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.9"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.9"
  arm64: "ghcr.io/home-assistant/arm64-base-python:3.9"
