---
name: Sleep Pad Monitor
version: 1.0.0
slug: sleep_pad_monitor
description: Sleep Pad Monitor
url: https://github.com/nott-smartbed/hassio-addons.git
uart: true
hassio_api: true
homeassistant_api: true
options:
  hassio_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNDZhNzUzMThmYTg0YjYxOGJiYmJlNDU5OWZlNGMyZiIsImlhdCI6MTczNTI4NDk3MiwiZXhwIjoyMDUwNjQ0OTcyfQ.4hJb_uC6jnUzGvKODSKZEXHWEqs3D6Yivp9Vx2POIiM
  serial_port: /dev/tty.usbserial-0001
  baud_rate: 115200
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  hassio_token: str
  serial_port: str
  baud_rate: int
devices:
  - /dev/tty.usbserial-0001